require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe LocaleFilesController do

  # This should return the minimal set of attributes required to create a valid
  # LocaleFile. As you add validations to LocaleFile, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all locale_files as @locale_files" do
      locale_file = LocaleFile.create! valid_attributes
      get :index
      assigns(:locale_files).should eq([locale_file])
    end
  end

  describe "GET show" do
    it "assigns the requested locale_file as @locale_file" do
      locale_file = LocaleFile.create! valid_attributes
      get :show, :id => locale_file.id.to_s
      assigns(:locale_file).should eq(locale_file)
    end
  end

  describe "GET new" do
    it "assigns a new locale_file as @locale_file" do
      get :new
      assigns(:locale_file).should be_a_new(LocaleFile)
    end
  end

  describe "GET edit" do
    it "assigns the requested locale_file as @locale_file" do
      locale_file = LocaleFile.create! valid_attributes
      get :edit, :id => locale_file.id.to_s
      assigns(:locale_file).should eq(locale_file)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new LocaleFile" do
        expect {
          post :create, :locale_file => valid_attributes
        }.to change(LocaleFile, :count).by(1)
      end

      it "assigns a newly created locale_file as @locale_file" do
        post :create, :locale_file => valid_attributes
        assigns(:locale_file).should be_a(LocaleFile)
        assigns(:locale_file).should be_persisted
      end

      it "redirects to the created locale_file" do
        post :create, :locale_file => valid_attributes
        response.should redirect_to(LocaleFile.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved locale_file as @locale_file" do
        # Trigger the behavior that occurs when invalid params are submitted
        LocaleFile.any_instance.stub(:save).and_return(false)
        post :create, :locale_file => {}
        assigns(:locale_file).should be_a_new(LocaleFile)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        LocaleFile.any_instance.stub(:save).and_return(false)
        post :create, :locale_file => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested locale_file" do
        locale_file = LocaleFile.create! valid_attributes
        # Assuming there are no other locale_files in the database, this
        # specifies that the LocaleFile created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        LocaleFile.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => locale_file.id, :locale_file => {'these' => 'params'}
      end

      it "assigns the requested locale_file as @locale_file" do
        locale_file = LocaleFile.create! valid_attributes
        put :update, :id => locale_file.id, :locale_file => valid_attributes
        assigns(:locale_file).should eq(locale_file)
      end

      it "redirects to the locale_file" do
        locale_file = LocaleFile.create! valid_attributes
        put :update, :id => locale_file.id, :locale_file => valid_attributes
        response.should redirect_to(locale_file)
      end
    end

    describe "with invalid params" do
      it "assigns the locale_file as @locale_file" do
        locale_file = LocaleFile.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        LocaleFile.any_instance.stub(:save).and_return(false)
        put :update, :id => locale_file.id.to_s, :locale_file => {}
        assigns(:locale_file).should eq(locale_file)
      end

      it "re-renders the 'edit' template" do
        locale_file = LocaleFile.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        LocaleFile.any_instance.stub(:save).and_return(false)
        put :update, :id => locale_file.id.to_s, :locale_file => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested locale_file" do
      locale_file = LocaleFile.create! valid_attributes
      expect {
        delete :destroy, :id => locale_file.id.to_s
      }.to change(LocaleFile, :count).by(-1)
    end

    it "redirects to the locale_files list" do
      locale_file = LocaleFile.create! valid_attributes
      delete :destroy, :id => locale_file.id.to_s
      response.should redirect_to(locale_files_url)
    end
  end

end
